version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: my-mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: 123456az
      MYSQL_DATABASE: aiep
      MYSQL_USER: aiep
      MYSQL_PASSWORD: 123456az
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
volumes:
  mysql_data:
