name: Build and Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 23


      - name: Install dependencies
        run: npm install

      - name: SSH - Deploy Backend
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            export NVM_DIR="$HOME/.nvm"
            [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
            nvm use 23 || nvm install 23
            cd /home/ubuntu/aiep-it/api-services

             cd /home/ubuntu/aiep-it/api-services
            git pull
            npm install
            npm run sync:pull

            export PATH="$PATH:$HOME/.npm-global/bin"
            pm2 restart api || pm2 start "npm run start" --name "api"

